name: greeter
on:
  pullrequest:
    branches:
      - main
jobs:
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build
      run: ./tool/build.sh
